export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  INSTITUTION_ADMIN = 'INSTITUTION_ADMIN',
  COORDINATOR = 'COORDINATOR',
  TEACHER = 'TEACHER',
  STUDENT = 'STUDENT',
  PARENT = 'PARENT',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
  NOT_INFORMED = 'NOT_INFORMED',
}

export enum RequestedProfileType {
  TEACHER = 'TEACHER',
  STUDENT = 'STUDENT',
  PARENT = 'PARENT',
}

export interface TeacherProfile {
  id: string;
  userId: string;
  specialization?: string;
  degree?: string;
  registrationNumber?: string;
  hireDate?: string;
  isActive: boolean;
}

export interface StudentProfile {
  id: string;
  userId: string;
  registrationNumber: string;
  enrollmentNumber?: string;
  enrollmentDate: string;
  isActive: boolean;
  
  // Novos campos acadêmicos
  situacao?: string;
  escola?: string;
  unidade?: string;
  anoLetivo?: string;
  curso?: string;
  serie?: string;
  turma?: string;
  modalidade?: string;
  turno?: string;
  observacoes?: string;
  
  // Relacionamentos
  healthRecord?: Record<string, any>; // Tipo mais específico pode ser criado depois
  transportation?: Record<string, any>;
}

export interface ParentProfile {
  id: string;
  userId: string;
  occupation?: string;
  isActive: boolean;
}

export interface ParentStudent {
  id: string;
  parentId: string;
  studentId: string;
  relationship: string; // "pai", "mãe", "tutor", "responsável legal", etc.
  isPrimary: boolean; // Backend usa isPrimary, não isPrimaryContact
  createdAt: string;
  updatedAt: string;
  parent?: {
    id: string;
    userId: string;
    user: User;
  };
  student?: {
    id: string;
    userId: string;
    user: User;
  };
}

export interface CreateParentStudentDto {
  parentId: string;
  studentId: string;
  relationship: string;
  isPrimaryContact?: boolean;
}

export interface UpdateParentStudentDto {
  relationship?: string;
  isPrimaryContact?: boolean;
}

export interface User {
  id: string;
  email: string;
  role: UserRole;
  firstName: string;
  lastName: string;
  cpf?: string;
  rg?: string;
  rgEmissor?: string;
  rgEmissao?: string;
  socialName?: string;
  nacionalidade?: string;
  naturalidade?: string;
  phone?: string;
  telefoneFixo?: string;
  birthDate?: string;
  gender?: Gender;
  avatar?: string;
  address?: string;
  numero?: string;
  complemento?: string;
  bairro?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  isActive: boolean;
  emailVerified: boolean;
  requestedProfileType?: string; // Profile type requested during self-registration
  institutionId: string;
  createdAt: string;
  updatedAt: string;

  // Multiple profiles support
  teacherProfile?: TeacherProfile;
  studentProfile?: StudentProfile;
  parentProfile?: ParentProfile;

  // Available profiles based on existing profiles
  availableProfiles?: UserRole[];

  // Currently active profile (for users with multiple profiles)
  activeProfile?: UserRole;

  // Force password update on first login
  mustChangePassword?: boolean;

  // Parent-Student relationships
  children?: ParentStudent[]; // When user is a parent
  parents?: ParentStudent[]; // When user is a student
}

export interface AuthResponse {
  accessToken: string;
  refreshToken: string;
  user: User;
}

export interface LoginCredentials {
  email: string;
  password: string;
}

export interface CreateUserDto {
  email: string;
  password?: string; // Made optional if autogenerated
  role: UserRole;
  firstName: string;
  lastName: string;
  cpf?: string;
  rg?: string;
  rgEmissor?: string;
  rgEmissao?: string;
  socialName?: string;
  nacionalidade?: string;
  naturalidade?: string;
  phone?: string;
  telefoneFixo?: string;
  birthDate?: string;
  gender?: Gender;
  address?: string;
  numero?: string;
  complemento?: string;
  bairro?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  isActive?: boolean;
  institutionId?: string;
  institutionIds?: string[];
  
  // Health Info
  tipoSanguineo?: string;
  convenioMedico?: string;
  alergias?: string;
  medicamentos?: string;
  necessidadesEspeciais?: string;
  restricoesAlimentares?: string;
  contatoEmergencia?: string;

  // Transport Info
  usaTransporte?: string;
  tipoTransporte?: string;
  empresaTransporte?: string;
  motoristaTransporte?: string;
  rotaTransporte?: string;

  // Student specific flattened fields (from form)
  situacao?: string;
  escola?: string;
  unidade?: string;
  anoLetivo?: string;
  curso?: string;
  serie?: string;
  turma?: string;
  modalidade?: string;
  turno?: string;
  dataMatricula?: string;
  observacoes?: string;

  healthInfo?: Record<string, any>;
  transportInfo?: Record<string, any>;
  responsaveis?: any[];
  specialization?: string;
  degree?: string;
  registrationNumber?: string;
  hireDate?: string;
  occupation?: string;
  subjectIds?: string[];
  linkedStudents?: Array<{
    studentId: string;
    studentUserId?: string;
    studentName?: string;
    relationship: string;
    isPrimary?: boolean;
    notificacoes?: boolean;
    podeRetirar?: boolean;
  }>;
}

export interface RegisterData {
  name: string;
  email: string;
  password: string;
  role: UserRole;
  institutionId: string;
}

export interface PublicRegisterData {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  institutionId: string;
  requestedProfileType: RequestedProfileType;
  cpf?: string;
  phone?: string;
  birthDate?: string;
  gender?: Gender;
  address?: string;
  city?: string;
  state?: string;
  zipCode?: string;
}

export interface UpdateUserData {
  firstName?: string;
  lastName?: string;
  email?: string;
  cpf?: string;
  rg?: string;
  rgEmissor?: string;
  rgEmissao?: string;
  socialName?: string;
  nacionalidade?: string;
  naturalidade?: string;
  phone?: string;
  telefoneFixo?: string;
  birthDate?: string;
  gender?: Gender;
  address?: string;
  numero?: string;
  complemento?: string;
  bairro?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  isActive?: boolean;

  // Student specific flattened fields (from form)
  situacao?: string;
  escola?: string;
  unidade?: string;
  anoLetivo?: string;
  curso?: string;
  serie?: string;
  turma?: string;
  modalidade?: string;
  turno?: string;
  dataMatricula?: string;
  observacoes?: string;

  healthInfo?: Record<string, any>;
  transportInfo?: Record<string, any>;
  responsaveis?: any[];
  institutionId?: string;
  institutionIds?: string[];
  password?: string;
  specialization?: string;
  degree?: string;
  registrationNumber?: string;
  hireDate?: string;
  occupation?: string;
  subjectIds?: string[];
  linkedStudents?: Array<{
    studentId: string;
    studentUserId?: string;
    studentName?: string;
    relationship: string;
    isPrimary?: boolean;
    notificacoes?: boolean;
    podeRetirar?: boolean;
  }>;
}

export interface ChangePasswordData {
  currentPassword: string;
  newPassword: string;
}

export interface AdminResetPasswordData {
  newPassword: string;
}

export interface PaginatedUsers {
  data: User[];
  meta: {
    total: number;
    page: number;
    limit: number;
    totalPages: number;
    hasNextPage: boolean;
    hasPreviousPage: boolean;
  };
}
